// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2642.myRobot.subsystems;

import org.usfirst.frc2642.myRobot.RobotMap;
import org.usfirst.frc2642.myRobot.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.interfaces.Accelerometer;


/**
 *
 */
public class Lift extends Subsystem {
	
    Talon lift = RobotMap.liftMotor;
    DigitalInput topLimit = RobotMap.topLimit;
    DigitalInput bottomLimit = RobotMap.bottomLimit;
    DigitalInput recieve = RobotMap.toteInRobot;
    DigitalInput lot = RobotMap.lotOfTotes;
    Encoder liftEncoder = RobotMap.liftEncoder;
    Encoder backEncoder = RobotMap.backLiftEncoder;
    Encoder frontEncoder = RobotMap.frontLiftEncoder;
    
    
    /*
    public static DigitalInput topLimit;
    public static DigitalInput bottomLimit;
    public static DigitalInput toteInRobot;
    public static DigitalInput lotOfTotes;
    public static Encoder liftEncoder;
    public static Encoder backLiftEncoder;
    public static Encoder frontLiftEncoder;
	 */

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new MecanumDefault());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void moveLift(double speed) {
    	lift.set(speed);
    }
    
    
    
    
}

